import Head from "next/head";
import Card from "@/components/Card";
const HomePage = () => {
  return (
    <>
      <Head>
        {" "}
        <title>Home Page</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className=" flex relative">
        <div className="bg-white/80 lg:flex w-0 lg:w-96 h-screen justify-start md:pl-4  lg:visible flex-col backdrop-blur-sm hidden">
          <h1 className="text-4xl font-ubuntu font-semibold">Dashboard</h1>
          <ul>
            <li>
              <button>location</button>
            </li>
            <li>
              <button>location</button>
            </li>
            <li>
              <button>Location</button>
            </li>
            <li>
              <button>Location</button>
            </li>
          </ul>
        </div>
        {/* //card content// */}
        <div className="flex-auto h-screen overflow-y-scroll grid grid-cols-1 xl:grid-cols-2 place-items-center space-y-4">
          <header className="static top-0 w-full bg-white/80 backdrop-blur-sm  lg:hidden resize-none">
            Dashboard
          </header>
          <Card
            title={"yes bitch"}
            content={
              "This is a fuck load of content that I am adding to test just how good or not good this is"
            }
            //plug <Image> as child prop
          />
          <Card
            title={"yes bitch"}
            content={
              "This is a fuck load of content that I am adding to test just how good or not good this is"
            }
            //plug <Image> as child prop
          />
          <Card
            title={"yes bitch"}
            content={
              "This is a fuck load of content that I am adding to test just how good or not good this is"
            }
            //plug <Image> as child prop
          />
          <Card
            title={"yes bitch"}
            content={
              "This is a fuck load of content that I am adding to test just how good or not good this is"
            }
            //plug <Image> as child prop
          />
          <Card
            title={"yes bitch"}
            content={
              "This is a fuck load of content that I am adding to test just how good or not good this is"
            }
            //plug <Image> as child prop
          />
          <Card
            title={"yes bitch"}
            content={
              "This is a fuck load of content that I am adding to test just how good or not good this is"
            }
            //plug <Image> as child prop
          />
        </div>
        <nav className="absolute bottom-0 w-full bg-white/80 backdrop-blur-sm  lg:invisible resize-none">
          <ul className="flex">
            <li>
              <button>location</button>
            </li>
            <li>
              <button>location</button>
            </li>
            <li>
              <button>Location</button>
            </li>
            <li>
              <button>Location</button>
            </li>
          </ul>
        </nav>
      </main>
    </>
  );
};

export default HomePage;
